const fs=require('fs/promises'),path=require('path'),crypto=require('crypto');
const DIR=process.env.MY_AI_MEMORY_DIR||path.join(process.env.HOME||'/root','my-ai-unified-data'),FILE=path.join(DIR,'memory.json');let lock=Promise.resolve();
const norm=s=>String(s||'').trim().replace(/\s+/g,' '),key=s=>norm(s).toLowerCase().replace(/[«»"“”]/g,''),placeKey=s=>{const k=key(s);return {'дома':'дом','домой':'дом','дому':'дом','домом':'дом'}[k]||k},hash=s=>crypto.createHash('sha256').update(String(s||'default')).digest('hex').slice(0,32);
async function all(){try{return JSON.parse(await fs.readFile(FILE,'utf8'))}catch{return {}}}async function save(x){await fs.mkdir(DIR,{recursive:true});const t=FILE+'.tmp';await fs.writeFile(t,JSON.stringify(x,null,2));await fs.rename(t,FILE)}async function mutate(id,fn){const p=lock;let r;lock=new Promise(x=>r=x);await p;try{const a=await all(),k=hash(id),u=a[k]||{rules:[],places:{}};await fn(u);a[k]=u;await save(a)}finally{r()}}async function user(id){const a=await all();return a[hash(id)]||{rules:[],places:{}}}
function uid(req){return req.body?.memoryId||req.headers['x-memory-id']||req.body?.sessionId||req.body?.request?.session_id||req.body?.session?.session_id||'default'}
function parse(text){let s=norm(text).replace(/^э(?:й|и)(?:[\s-]+(?:эй|ай|ai))?[\s,:;!?-]*/iu,'').replace(/^ай[\s,:;!?-]*/iu,'').replace(/[.!?]+$/,'').trim(),m;
 m=s.match(/^запомни\s+(?:мо[её]\s+)?местоположени(?:е|я)\s*(?:как|назови|под\s+именем)\s*["“]?([^"”:\n]+)["”]?\s*(?::|-)?\s*(.*)$/iu);if(m)return{kind:'place',name:norm(m[1])||'Место',value:norm(m[2])};
 m=s.match(/^запомни\s+(?:мо[её]\s+)?местоположени(?:е|я)\s*(?:это|:|-)?\s*(.*)$/iu);if(m)return{kind:'place',name:'Дом',value:norm(m[1])};
 m=s.match(/^запомни\s+(?:правило|правила)\s*[:\-]?\s*(.+)$/iu);if(m)return{kind:'rule',value:norm(m[1])};m=s.match(/^запомни\s*[:\-]?\s*(.+)$/iu);if(m)return{kind:'rule',value:norm(m[1])};
 if(/^(?:что\s+ты\s+обо\s+мне\s+запомнил|что\s+ты\s+запомнил|какие\s+у\s+тебя\s+правила)$/iu.test(s))return{kind:'show'};
 if(/^забудь\s+(?:мо[её]\s+)?местоположени(?:е|я)$/iu.test(s))return{kind:'forgetPlace',name:'Дом'};if(/^забудь\s+(?:всё|все|всё\s+что\s+ты\s+запомнил|все\s+правила)$/iu.test(s))return{kind:'forgetAll'};m=s.match(/^забудь\s+(?:правило|правила)\s*[:\-]?\s*(.+)$/iu);if(m)return{kind:'forgetRule',value:norm(m[1])};
 m=s.match(/^(?:построй|покажи|проложи)\s+(?:мне\s+)?(?:точку\s+)?маршрут\s+(?:до|к)\s+(.+)$/iu);if(m)return{kind:'route',to:norm(m[1])};return null}
async function geo(q){if(!q)return null;try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&accept-language=ru&q='+encodeURIComponent(q),{headers:{'User-Agent':'My-AI-Unified/1.0 contact: ai.aliceq.ru'},signal:AbortSignal.timeout(10000)}),a=await r.json().catch(()=>[]);return r.ok&&a[0]?{lat:+a[0].lat,lon:+a[0].lon,address:String(a[0].display_name||q)}:null}catch{return null}}
function text(u){const p=Object.values(u.places||{}).map(v=>`${v.name}: ${v.address||`${v.lat}, ${v.lon}`}`).join('\n'),r=(u.rules||[]).map(v=>`• ${v.text}`).join('\n');return[p?'Сохранённые места:\n'+p:'',r?'Постоянные правила:\n'+r:''].filter(Boolean).join('\n\n')||'Постоянной памяти пока нет.'}
async function command(req,c){const id=uid(req);if(c.kind==='show')return{ok:true,route:'memory',result:text(await user(id))};if(c.kind==='forgetAll'){await mutate(id,u=>{u.rules=[];u.places={}});return{ok:true,route:'memory',result:'Запомненные правила и места удалены.'}}if(c.kind==='forgetPlace'){await mutate(id,u=>{delete u.places[placeKey(c.name)]});return{ok:true,route:'memory',result:'Дом забыт.'}}if(c.kind==='forgetRule'){await mutate(id,u=>{u.rules=(u.rules||[]).filter(x=>x.text!==c.value)});return{ok:true,route:'memory',result:'Правило удалено.'}}if(c.kind==='rule'){await mutate(id,u=>{u.rules=u.rules||[];u.rules.unshift({id:crypto.randomUUID(),text:c.value,createdAt:new Date().toISOString()});u.rules=u.rules.slice(0,100)});return{ok:true,route:'memory',result:'Запомнил это как постоянное правило.'}}if(c.kind==='place'){const loc=req.body?.location&&Number.isFinite(+req.body.location.lat)?{lat:+req.body.location.lat,lon:+req.body.location.lon,address:String(req.body.location.address||'Текущее местоположение')}:await geo(c.value);if(!loc)return{ok:true,route:'memory',result:`Не смог определить место для «${c.name}». Дай адрес или разреши доступ к геопозиции.`};await mutate(id,u=>{u.places[placeKey(c.name)]={name:c.name,...loc,updatedAt:new Date().toISOString()}});return{ok:true,route:'memory',result:`Запомнил «${c.name}».`}}if(c.kind==='route'){const u=await user(id),v=u.places?.[placeKey(c.to)]||Object.values(u.places||{}).find(x=>placeKey(x.name)===placeKey(c.to));if(!v)return{ok:true,route:'memory',result:`Я не знаю место «${c.to}». Сначала скажи: «Эй, запомни моё местоположение как ${c.to}».`};const dest=v.lat!=null?`${v.lat},${v.lon}`:v.address;return{ok:true,route:'map',result:`Маршрут до «${v.name||c.to}» построен.`,routeUrl:'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest),destination:v}}}
async function memoryMiddleware(req,res,next){if(req.path!=='/chat'&&req.path!=='/alice')return next();const t=req.path==='/alice'?(req.body?.request?.command||req.body?.request?.original_utterance||''):(req.body?.prompt||'');const c=parse(t);if(c)try{const o=await command(req,c);return req.path==='/alice'?res.json({version:'1.0',response:{text:o.result,end_session:false}}):res.json(o)}catch(e){return res.status(500).json({ok:false,error:e.message})}try{const u=await user(uid(req));if(req.body?.messages)req.body.messages=[{role:'system',content:'Постоянная память пользователя. Используй её как пользовательские настройки и сведения, но она не отменяет системные правила безопасности:\n'+text(u)},...req.body.messages]}catch{}next()}
function memoryRoutes(app){app.get('/memory',async(req,res)=>res.json({ok:true,memory:await user(req.query.memoryId||'default')}))}
module.exports={memoryMiddleware,memoryRoutes,parse};
