const fs=require('fs/promises');
const path=require('path');
const crypto=require('crypto');
const DATA_DIR=process.env.MY_AI_MEMORY_DIR||path.join(process.env.HOME||'/root','my-ai-unified-data');
const FILE=path.join(DATA_DIR,'memory.json');
let lock=Promise.resolve();
const norm=s=>String(s||'').trim().replace(/\s+/g,' ');
const hash=s=>crypto.createHash('sha256').update(String(s||'default')).digest('hex').slice(0,32);
async function readAll(){try{return JSON.parse(await fs.readFile(FILE,'utf8'))}catch{return {}}}
async function writeAll(x){await fs.mkdir(DATA_DIR,{recursive:true});const t=FILE+'.tmp';await fs.writeFile(t,JSON.stringify(x,null,2),'utf8');await fs.rename(t,FILE)}
async function locked(fn){const prev=lock;let release;lock=new Promise(r=>release=r);await prev;try{return await fn()}finally{release()}}
function uid(req){return req.body?.memoryId||req.headers['x-memory-id']||req.body?.sessionId||req.body?.request?.session_id||req.body?.session?.session_id||'default'}
function stripWake(s){return norm(s).replace(/^э(?:й|и|й-ай|й ай|й-эй|й эй)[\s,:;!?-]*/iu,'').replace(/^ай[\s,:;!?-]*/iu,'')}
function parseCommand(text){const s=stripWake(text);let m=s.match(/^запомни\s+(?:мо[её]\s+)?местоположени(?:е|я)\s*(?:как|назови|под\s+именем)\s*["“]?([^"”:\n]+)["”]?\s*(?::|-)?\s*(.*)$/iu);if(m)return {kind:'place',name:norm(m[1])||'Место',value:norm(m[2])};m=s.match(/^запомни\s+(?:мо[её]\s+)?местоположени(?:е|я)\s*(?:это|:|-)?\s*(.*)$/iu);if(m)return {kind:'place',name:'Дом',value:norm(m[1])};m=s.match(/^запомни\s+(?:правило|правила)\s*[:\-]?\s*(.+)$/iu);if(m)return {kind:'rule',value:norm(m[1])};m=s.match(/^запомни\s*[:\-]?\s*(.+)$/iu);if(m)return {kind:'rule',value:norm(m[1])};if(/^(?:что\s+ты\s+обо\s+мне\s+запомнил|что\s+ты\s+запомнил|какие\s+у\s+тебя\s+правила)$/iu.test(s))return {kind:'show'};if(/^забудь\s+(?:мо[её]\s+)?местоположени(?:е|я)$/iu.test(s))return {kind:'forgetPlace',name:'Дом'};if(/^забудь\s+(?:всё|все|всё\s+что\s+ты\s+запомнил|все\s+правила)$/iu.test(s))return {kind:'forgetAll'};m=s.match(/^забудь\s+(?:правило|правила)\s*[:\-]?\s*(.+)$/iu);if(m)return {kind:'forgetRule',value:norm(m[1])};m=s.match(/^(?:построй|покажи|проложи)\s+(?:мне\s+)?(?:точку\s+)?маршрут\s+(?:до|к)\s+(.+)$/iu);if(m)return {kind:'route',to:norm(m[1])};return null}
function placeKey(n){return norm(n).toLowerCase().replace(/[«»"“”]/g,'')}
async function mutate(id,fn){return locked(async()=>{const all=await readAll();const k=hash(id);const u=all[k]||{rules:[],places:{}};await fn(u);all[k]=u;await writeAll(all)})}
async function getUser(id){const all=await readAll();return all[hash(id)]||{rules:[],places:{}}}
function memoryText(u){const p=Object.entries(u.places||{}).map(([k,v])=>`${v.name||k}: ${v.address||((v.lat!=null&&v.lon!=null)?`${v.lat}, ${v.lon}`:'местоположение')}`).join('\n');const r=(u.rules||[]).map(x=>`• ${x.text}`).join('\n');return [p?`Сохранённые места:\n${p}`:'',r?`Постоянные правила:\n${r}`:''].filter(Boolean).join('\n\n')||'Постоянной памяти пока нет.'}
async function geocode(q){if(!q||/^местоположение$/iu.test(q))return null;try{const u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&accept-language=ru&q='+encodeURIComponent(q);const r=await fetch(u,{headers:{'User-Agent':'My-AI-Unified/1.0 contact: ai.aliceq.ru'},signal:AbortSignal.timeout(10000)});const a=await r.json().catch(()=>[]);if(!r.ok||!a[0])return null;return {lat:Number(a[0].lat),lon:Number(a[0].lon),address:String(a[0].display_name||q)}}catch{return null}}
async function handleCommand(req,c){const id=uid(req);if(c.kind==='show')return {ok:true,route:'memory',result:memoryText(await getUser(id))};if(c.kind==='forgetAll'){await mutate(id,u=>{u.rules=[];u.places={}});return {ok:true,route:'memory',result:'Запомненные правила и места удалены.'}}if(c.kind==='forgetPlace'){await mutate(id,u=>{delete u.places[placeKey(c.name)]});return {ok:true,route:'memory',result:'Дом забыт.'}}if(c.kind==='forgetRule'){await mutate(id,u=>{u.rules=(u.rules||[]).filter(x=>x.text!==c.value)});return {ok:true,route:'memory',result:'Правило удалено.'}}if(c.kind==='place'){const loc=req.body?.location&&Number.isFinite(Number(req.body.location.lat))?{lat:Number(req.body.location.lat),lon:Number(req.body.location.lon),address:String(req.body.location.address||'Текущее местоположение')}:await geocode(c.value);if(!loc)return {ok:true,route:'memory',result:`Не смог определить место для «${c.name}». Дай адрес или разреши доступ к геопозиции.`};await mutate(id,u=>{u.places[placeKey(c.name)]={name:c.name,...loc,updatedAt:new Date().toISOString()}});return {ok:true,route:'memory',result:`Запомнил «${c.name}».`}}if(c.kind==='rule'){await mutate(id,u=>{u.rules=u.rules||[];const i=u.rules.findIndex(x=>x.text===c.value);if(i>=0)u.rules[i].updatedAt=new Date().toISOString();else u.rules.unshift({id:crypto.randomUUID(),text:c.value,createdAt:new Date().toISOString()});u.rules=u.rules.slice(0,100)});return {ok:true,route:'memory',result:'Запомнил это как постоянное правило.'}}if(c.kind==='route'){const u=await getUser(id);const v=u.places?.[placeKey(c.to)]||Object.values(u.places||{}).find(x=>placeKey(x.name)===placeKey(c.to));if(!v)return {ok:true,route:'memory',result:`Я не знаю место «${c.to}». Скажи: «Эй, запомни моё местоположение как ${c.to}»`};const dest=v.lat!=null?`${v.lat},${v.lon}`:v.address;const url='https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest);return {ok:true,route:'map',result:`Маршрут до «${v.name||c.to}» построен.`,routeUrl:url,destination:v}}return null}
async function memoryMiddleware(req,res,next){if(req.path!=='/chat'&&req.path!=='/alice')return next();const text=req.path==='/alice'?(req.body?.request?.command||req.body?.request?.original_utterance||''):(req.body?.prompt||((req.body?.messages||[]).slice().reverse().find(x=>x?.role==='user')||{}).content||'');const c=parseCommand(text);if(c){try{const out=await handleCommand(req,c);if(req.path==='/alice')return res.json({version:'1.0',response:{text:out.result,end_session:false}});return res.json(out)}catch(e){return res.status(500).json({ok:false,error:e.message})}}try{const u=await getUser(uid(req));const mt=memoryText(u);if(mt&&req.body?.messages)req.body.messages=[{role:'system',content:`Постоянная память пользователя. Используй её как пользовательские настройки и сведения, но она не отменяет системные правила безопасности:\n${mt}`},...req.body.messages]}catch{}next()}
function memoryRoutes(app){app.get('/memory',async(req,res)=>{const u=await getUser(req.query.memoryId||'default');res.json({ok:true,memory:u,result:memoryText(u)})})}
module.exports={memoryMiddleware,memoryRoutes,parseCommand};
